---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dambusns/public_html/npi
    - test -d "$DEPLOYPATH" || mkdir -p "$DEPLOYPATH"
    - npm install --no-audit --no-fund
    - npm run build
    - rsync -a --delete --exclude=.well-known/ dist/ $DEPLOYPATH/
