---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dambusns/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - npm install
    - npm run build
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH/.htaccess
