backend:
  name: github
  repo: dambus/npi-3
  branch: main
  base_url: https://npi-oauth-proxy.onrender.com # render URL
  auth_endpoint: /auth
  client_id: Ov23liATgrsKhrZZwzrC

media_folder: public/media
public_folder: /media
publish_mode: simple

collections:
  - name: projects
    label: Projects
    label_singular: Project
    editor:
      preview: false
    files:
      - name: projectsData
        label: Projects Data
        file: src/data/projects.json
        format: json
        fields:
          - label: Projects
            name: projects
            widget: list
            label_singular: Project
            summary: "{{name}} ({{year}})"
            allow_add: true
            collapsed: true
            fields:
              - label: Name
                name: name
                widget: string
              - label: Slug
                name: slug
                widget: string
                hint: Used in URLs like /projects/<slug>. Leave blank to auto-generate from the name.
                required: false
              - label: Client
                name: client
                widget: string
              - label: Category
                name: category
                widget: string
              - label: Year
                name: year
                widget: number
                value_type: int
                min: 1900
                max: 2100
              - label: Short Description
                name: shortDescription
                widget: text
              - label: Description
                name: description
                widget: list
                label_singular: Paragraph
                summary: "{{fields.paragraph | truncate(80)}}"
                field:
                  label: Paragraph
                  name: paragraph
                  widget: text
              - label: Hero Image
                name: heroImage
                widget: object
                fields:
                  - label: Image
                    name: src
                    widget: image
                  - label: Alt Text
                    name: alt
                    widget: string
              - label: Gallery
                name: gallery
                widget: list
                label_singular: Image
                summary: "{{fields.alt}}"
                fields:
                  - label: Image
                    name: src
                    widget: image
                  - label: Alt Text
                    name: alt
                    widget: string
                  - label: Caption
                    name: caption
                    widget: string
                    required: false
              - label: Related Projects
                name: relatedSlugs
                widget: list
                required: false
                hint: Slugs of related projects to feature on the detail page carousel.
                field:
                  label: Related Project Slug
                  name: slug
                  widget: string
              - label: Metadata
                name: metadata
                widget: object
                fields:
                  - label: Internal ID
                    name: internalId
                    widget: string
                  - label: Status
                    name: status
                    widget: select
                    options:
                      - label: Published
                        value: published
                      - label: Draft
                        value: draft
                  - label: Project Manager
                    name: projectManager
                    widget: string
                    required: false
                  - label: Priority
                    name: priority
                    widget: select
                    required: false
                    options:
                      - label: Flagship
                        value: flagship
                      - label: Portfolio
                        value: portfolio
                      - label: Standard
                        value: standard
                  - label: Tags
                    name: tags
                    widget: list
                    required: false
                    field:
                      label: Tag
                      name: tag
                      widget: string
